type AdjustmentKey = "brightness" | "contrast" | "saturation" | "temperature";
const canvas = document.querySelector<HTMLCanvasElement>("#canvas")!;
const ctx = canvas.getContext("2d", { willReadFrequently: true })!;
const fileInput = document.querySelector<HTMLInputElement>("#fileInput")!;
const sliders = document.querySelector<HTMLDivElement>("#sliders")!;
const emptyState = document.querySelector<HTMLElement>("#emptyState")!;
const canvasWrap = document.querySelector<HTMLElement>("#canvasWrap")!;
const stageTools = document.querySelector<HTMLElement>("#stageTools")!;
const imageInfo = document.querySelector<HTMLElement>("#imageInfo")!;
const compareLabel = document.querySelector<HTMLElement>("#compareLabel")!;
const saveButton = document.querySelector<HTMLButtonElement>("#save")!;
const resetButton = document.querySelector<HTMLButtonElement>("#reset")!;
const settings: Record<AdjustmentKey, number> = { brightness: 0, contrast: 0, saturation: 0, temperature: 0 };
const controls: Array<{key: AdjustmentKey; label: string}> = [{key:"brightness",label:"明るさ"},{key:"contrast",label:"コントラスト"},{key:"saturation",label:"彩度"},{key:"temperature",label:"色温度"}];
let source: HTMLCanvasElement|null=null, rotation=0, flipX=1, flipY=1, fileName="photo";
controls.forEach(({key,label})=>{const row=document.createElement("label");row.className="slider-row";row.innerHTML=`<span>${label}</span><output id="${key}Value">0</output><input id="${key}" type="range" min="-100" max="100" value="0" disabled>`;sliders.append(row);row.querySelector("input")!.addEventListener("input",event=>{settings[key]=Number((event.target as HTMLInputElement).value);row.querySelector("output")!.value=settings[key]>0?`+${settings[key]}`:String(settings[key]);render()})});
function loadFile(file:File){if(!file.type.startsWith("image/"))return;const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{source=document.createElement("canvas");source.width=img.naturalWidth;source.height=img.naturalHeight;source.getContext("2d")!.drawImage(img,0,0);URL.revokeObjectURL(url);fileName=file.name.replace(/\.[^.]+$/,"");rotation=0;flipX=flipY=1;resetAdjustments();emptyState.hidden=true;canvasWrap.hidden=false;stageTools.hidden=false;document.querySelectorAll<HTMLButtonElement|HTMLInputElement>("button[disabled],#sliders input").forEach(el=>el.disabled=false);imageInfo.textContent=`${img.naturalWidth} × ${img.naturalHeight}px`;render()};img.src=url}
function render(original=false){if(!source)return;const quarter=Math.abs(rotation%180)===90;canvas.width=quarter?source.height:source.width;canvas.height=quarter?source.width:source.height;ctx.save();ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(rotation*Math.PI/180);ctx.scale(flipX,flipY);if(!original)ctx.filter=`brightness(${100+settings.brightness}%) contrast(${100+settings.contrast}%) saturate(${100+settings.saturation}%) sepia(${Math.abs(settings.temperature)*.12}%)`;ctx.drawImage(source,-source.width/2,-source.height/2);ctx.restore();if(!original&&settings.temperature){ctx.save();ctx.globalCompositeOperation="overlay";ctx.globalAlpha=Math.abs(settings.temperature)/250;ctx.fillStyle=settings.temperature>0?"#ff8a38":"#388cff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore()}}
function resetAdjustments(){controls.forEach(({key})=>{settings[key]=0;(document.querySelector(`#${key}`) as HTMLInputElement).value="0";(document.querySelector(`#${key}Value`) as HTMLOutputElement).value="0"})}
fileInput.addEventListener("change",()=>fileInput.files?.[0]&&loadFile(fileInput.files[0]));const dropZone=document.querySelector<HTMLElement>("#dropZone")!;["dragenter","dragover"].forEach(type=>dropZone.addEventListener(type,e=>{e.preventDefault();dropZone.classList.add("dragging")}));["dragleave","drop"].forEach(type=>dropZone.addEventListener(type,e=>{e.preventDefault();dropZone.classList.remove("dragging")}));dropZone.addEventListener("drop",e=>e.dataTransfer?.files[0]&&loadFile(e.dataTransfer.files[0]));document.querySelectorAll<HTMLButtonElement>("[data-action]").forEach(button=>button.addEventListener("click",()=>{const a=button.dataset.action;if(a==="rotateLeft")rotation-=90;if(a==="rotateRight")rotation+=90;if(a==="flipX")flipX*=-1;if(a==="flipY")flipY*=-1;render()}));resetButton.addEventListener("click",()=>{rotation=0;flipX=flipY=1;resetAdjustments();render()});const compare=document.querySelector<HTMLButtonElement>("#compare")!,showOriginal=()=>{render(true);compareLabel.hidden=false},showEdited=()=>{compareLabel.hidden=true;render()};compare.addEventListener("pointerdown",showOriginal);["pointerup","pointerleave","pointercancel"].forEach(type=>compare.addEventListener(type,showEdited));const dialog=document.querySelector<HTMLDialogElement>("#exportDialog")!;saveButton.addEventListener("click",()=>dialog.showModal());const format=document.querySelector<HTMLSelectElement>("#format")!,quality=document.querySelector<HTMLInputElement>("#quality")!;quality.addEventListener("input",()=>document.querySelector("#qualityValue")!.textContent=`${quality.value}%`);format.addEventListener("change",()=>document.querySelector<HTMLElement>("#qualityRow")!.hidden=format.value==="image/png");document.querySelector("#download")!.addEventListener("click",e=>{e.preventDefault();render();const ext=format.value.split("/")[1],a=document.createElement("a");a.download=`${fileName}-edited.${ext}`;a.href=canvas.toDataURL(format.value,Number(quality.value)/100);a.click();dialog.close()});
